#!/bin/bash
# Phase 1 — the same workload under four isolation settings, with startup and overhead measured.
# Runs as root inside the minimum lab tier. Output is the verification evidence, verbatim.
set -u
LAB=/var/lab; ROOTFS=$LAB/rootfs; mkdir -p $LAB
T=${T:-15}; N=${N:-10}
WL_SYS="stress-ng --pipe 1 -t ${T}s --metrics-brief"
WL_CPU="stress-ng --cpu 1 -t ${T}s --metrics-brief"
bogo() { grep -E '^stress-ng: metrc.*(pipe|cpu) ' | awk '{print $9}'; }   # bogo ops/s (real time)
now() { date +%s%N; }
startup() { # $1 = label, rest = command that runs /bin/true under the tier
  local label=$1; shift; local t0 t1 sum=0
  for i in $(seq 1 $N); do t0=$(now); "$@" >/dev/null 2>&1; t1=$(now); sum=$((sum + (t1-t0)/1000)); done
  echo "startup  $label  mean_us=$((sum / N))  (n=$N, /bin/true)"
}

echo "== tier 0: host kernel, no isolation =="
startup t0-host /bin/true
echo "syscall  t0-host  bogo_ops_s=$($WL_SYS 2>&1 | bogo)"
echo "cpu      t0-host  bogo_ops_s=$($WL_CPU 2>&1 | bogo)"

echo "== tier 1: namespaces + cgroups v2 by hand (unshare + chroot, no runtime) =="
CG=/sys/fs/cgroup/lab-t1; mkdir -p $CG
echo "+cpu +memory +pids" > /sys/fs/cgroup/cgroup.subtree_control 2>/dev/null || true
echo "200000 100000" > $CG/cpu.max; echo 512M > $CG/memory.max; echo 256 > $CG/pids.max
t1run() { # run a command inside fresh mount/uts/ipc/net/pid/cgroup namespaces, chroot into the rootfs, in the cgroup.
  # The exported rootfs has an EMPTY /dev and no /proc or /sys — a runtime populates those for you; by hand you do it yourself.
  # Join the cgroup BEFORE unsharing: inside a new cgroup namespace the host path is not visible and the write fails.
  printf '%s\n' "$*" > $LAB/t1cmd.sh
  ( echo $BASHPID > $CG/cgroup.procs; exec unshare --mount --uts --ipc --net --pid --fork --cgroup bash -c "hostname lab-t1; \
    mount -t proc proc $ROOTFS/proc; mount -t sysfs sysfs $ROOTFS/sys; mount -t tmpfs none $ROOTFS/dev; \
    mknod -m 666 $ROOTFS/dev/null c 1 3; mknod -m 666 $ROOTFS/dev/zero c 1 5; mknod -m 666 $ROOTFS/dev/urandom c 1 9; mknod -m 666 $ROOTFS/dev/random c 1 8; \
    cp $LAB/t1cmd.sh $ROOTFS/t1cmd.sh; exec chroot $ROOTFS /bin/sh /t1cmd.sh" )
}
startup t1-unshare t1run /bin/true
echo "cgroup   t1-unshare  cpu.max=$(cat $CG/cpu.max)  memory.max=$(cat $CG/memory.max)  pids.max=$(cat $CG/pids.max)"
( t1run "sleep 3" & ) ; sleep 1; echo "cgroup   t1-unshare  members_while_running=$(wc -l < $CG/cgroup.procs)  memory.current=$(cat $CG/memory.current)"; sleep 3
echo "ns       t1-unshare  $(t1run 'echo pid1=$$ hostname=$(hostname) ifaces=$(ls /sys/class/net | tr "\n" ",") procs=$(ls /proc | grep -c "^[0-9]")')"
echo "syscall  t1-unshare  bogo_ops_s=$(t1run "$WL_SYS" 2>&1 | bogo)"
echo "cpu      t1-unshare  bogo_ops_s=$(t1run "$WL_CPU" 2>&1 | bogo)"

echo "== tier 2: OCI runtime (runc), same rootfs, spec generated by runc =="
B=$LAB/bundle; rm -rf $B; mkdir -p $B; cp -a $ROOTFS $B/rootfs 2>/dev/null || cp -r $ROOTFS $B/rootfs
( cd $B && runc spec >/dev/null 2>&1 )
jq '.process.terminal=false | .root.readonly=false | .linux.resources.memory.limit=536870912 | .linux.resources.pids.limit=256 | .linux.resources.cpu.quota=200000 | .linux.resources.cpu.period=100000' $B/config.json > $B/c.json && mv $B/c.json $B/config.json
t2run() { jq --argjson a "$(printf '%s\n' "$@" | jq -R . | jq -s .)" '.process.args=$a' $B/config.json > $B/run.json && mv $B/run.json $B/config.json; ( cd $B && runc run lab-t2-$RANDOM ); }
startup t2-runc t2run /bin/true
echo "syscall  t2-runc  bogo_ops_s=$(t2run $WL_SYS 2>&1 | bogo)"
echo "cpu      t2-runc  bogo_ops_s=$(t2run $WL_CPU 2>&1 | bogo)"

echo "== tier 3: user-space kernel (gVisor runsc, systrap platform) via podman =="
t3run() { podman run --rm --runtime /usr/local/bin/runsc --memory 512m --cpus 2 --pids-limit 256 localhost/lab-env "$@"; }
echo "platform t3-gvisor  $(runsc --version | head -1)  $(t3run dmesg 2>/dev/null | head -1)"
startup t3-gvisor t3run /bin/true
echo "syscall  t3-gvisor  bogo_ops_s=$(t3run $WL_SYS 2>&1 | bogo)"
echo "cpu      t3-gvisor  bogo_ops_s=$(t3run $WL_CPU 2>&1 | bogo)"

echo "== tier 4: microVM (Firecracker) =="
echo "kvm      t4-firecracker  /dev/kvm: $(ls /dev/kvm 2>&1)  -> SPECCED-NOT-RUN on this tier"
